services:
  cloud-rec:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: -Dspring.profiles.active=opensource
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql-local

  mysql-local:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - "db-data:/var/lib/mysql"
      - "$PWD/db/my.cnf:/etc/my.cnf"
      - "$PWD/db/:/docker-entrypoint-initdb.d/"
    ports:
      - "3306:3306"
volumes:
  db-data: {}
